CREATE TABLE questions (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(255) NOT NULL,
    question_title VARCHAR(255) NOT NULL,
    option1 VARCHAR(255) NOT NULL,
    option2 VARCHAR(255) NOT NULL,
    option3 VARCHAR(255) NOT NULL,
    option4 VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(255) NOT NULL
);
INSERT INTO questions (topic, question_title, option1, option2, option3, option4, correct_answer)
VALUES (
    'SQL',
    'What is the full form of SQL?',
    'Structured Query List',
    'Structure Query Language',
    'Sample Query Language',
    'None of these',
    'Structure Query Language'),
    (
        'SQL',
        'Which of the following is not a valid SQL type?',
        'FLOAT',
        'NUMERIC',
        'DECIMAL',
        'CHARACTER',
        'DECIMAL'),
    (
         'SQL',
         'Which of the following is not a DDL command?',
         'TRUNCATE',
         'ALTER',
         'CREATE',
         'UPDATE',
         'UPDATE'),
    (
         'SQL',
         'Which of the following are TCL commands?',
         'COMMIT and ROLLBACK',
         'UPDATE and TRUNCATE',
         'SELECT and INSERT',
         'GRANT and REVOKE',
         'COMMIT and ROLLBACK'),
    (
         'SQL',
         'Which statement is used to delete all rows in a table without having the action logged?',
         'DELETE',
         'REMOVE',
         'DROP',
         'TRUNCATE',
         'TRUNCATE'),
    (
         'Java',
         'Which of the following is not a Java features?',
         'Dynamic',
         'Architecture Neutral',
         'Use of pointers',
         'Object-oriented',
         'Use of pointers'),
    (
         'Java',
         '_____ is used to find and fix bugs in the Java programs.',
         'JVM',
         'JRE',
         'JDK',
         'JDB',
         'JDB'),
    (
         'Java',
         'What is the return type of the hashCode() method in the Object class?',
         'Object',
         'int',
         'long',
         'void',
         'int'),
    (
         'Java',
         'Which option is false about the final keyword?',
         'A final method cannot be overridden in its subclasses.',
         'A final class cannot be extended.',
         'A final class cannot extend other classes.',
         'A final method can be inherited.',
         'A final class cannot extend other classes.'),
    (
         'Java',
         'Which of these classes are the direct subclasses of the Throwable class?',
         'RuntimeException and Error class',
         'Exception and VirtualMachineError class',
         'Error and Exception class',
         'IOException and VirtualMachineError class',
         'Error and Exception class');